### ISSUE TITLE
RSparkling section 

### ISSUE THREAD

**Issue by navdeep-G** [r-spark/the-r-in-spark#1]
* Would it be useful to have a `RSparkling` section? If so, I can help.

**Comment by javierluraschi** [comment]
@navdeep-G yes, that would be great! I would add a new chapter named `h2o.Rmd`, I know that you would mostly cover `rsparkling`, but it would make more sense to name the chapter `H2O` since users would want to read about `rsparkling` in the context of `H2O`.

Let me know if you want me to talk to someone in H2O about this, I think it would be fine but definitely let me know if there is something to sort out.

**Comment by navdeep-G** [comment]
Yes, that makes sense. But since the book itself is about R and Spark it should really tie in H2O Sparkling Water as this package brings H2O to Spark. This can all be put together via rsparkling. Does that make sense? So the chapter will be called “H2O” but all examples are shown through the lense of rsparkling, which in turn showcases Sparkling Water (H2O and Spark). 

Thoughts @jakubhava @mmalohlava ?

**Comment by javierluraschi** [comment]
@navdeep-G Yes, for sure. The entire chapter would be about `rsparkling`, I just think it would be hard for people to understand what this chapter is about if we name it `rsparkling`.

It would also require a very brief intro to what H2O is, since many will be learning about Spark/H2O for the first time, it would make sense to mention in the intro that there are other ways of using H2O in Spark and that H2O itself does not even require Spark. I would add the appropriate references for those that might be interested in learning more about H2O itself.

However, once that's out of the way, everything else in the chapter would be about `rsparkling`.

**Comment by navdeep-G** [comment]
@javierluraschi Makes sense. I can compile something. Is there a timeline?

**Comment by javierluraschi** [comment]
@navdeep-G yes, we are trying to get this done by January 1st since we would like to do editing only after that date.

**Comment by javierluraschi** [comment]
Section added!
